# Generated by Django 3.2 on 2022-03-03 14:51

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_merge_20220303_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='other_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(default=None, error_messages={'unique': 'A user with that Phone number already exists.'}, help_text='Example : 09125573688', max_length=11, unique=True, validators=[user.models.MobileNumberValidator()], verbose_name='Phone Number'),
        ),
    ]
